config/routes.rb
Rails.application.routes.draw do
  root to: 'cards#index'
  resources :cards, expect: [:destroy]
  delete '/cardsdestroy', to: 'cards#destroy', as: 'cardsdestroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  validates :name, :rarity, :image_url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @q = ::Card.ransack(params[:q])
    @cards = @q.result(distinct: true)
  end

  def create
    ::Cards::Import.new.process
    redirect_to root_path
  end

  def destroy
    ::Card.destroy_all
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/index.html.erb
<div class="top-container">
  <%= form_tag(cards_path, method: :post) do %>
    <%= submit_tag('Create Backup', class: 'btn draw-border') %>
  <% end %>
  <%= form_tag(cardsdestroy_path, method: :delete) do %>
    <%= submit_tag('Purge Backup ', class: 'btn draw-border') %>
  <% end %>

<%= search_form_for @q do |f| %>
  <%= f.label :name_cont %>
  <%= f.search_field :name_cont %>
  </br>
  <%= f.label :hit_point_eq %>
  <%= f.search_field :hp_eq %>
  </br>
  <%= f.label :rarity_eq %>
  <%= f.search_field :rarity_eq %>
  </br>
  <%= f.submit 'Search Backup', class: 'btn draw-border' %>
<% end %>
</div>
<div class="container">
  <% @cards.each do |card| %>
    <div class="card">
      <img src=<%= card.image_url %> alt="Person" class="card__image">
      <p class="card__name"><%= card.name %></p>
      <div class="grid-container">
        <div class="grid-child-posts">
          <%= card.rarity %>
        </div>
        <div class="grid-child-followers">
          <%= card.hp%>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokemonCards</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>